# Generated by Django 3.2.5 on 2021-07-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='family',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('family_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('member_count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=16, null=True)),
                ('gender', models.CharField(choices=[('m', 'man'), ('w', 'woman')], max_length=1)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('child_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_of', to='family.family')),
                ('parent_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_of', to='family.family')),
                ('pg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.package')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
