# Generated by Django 3.2.5 on 2021-07-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='family',
            name='password',
        ),
    ]
