version: '3.7'

services:
  django:
    build: .
    #  command: python project/manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mysqldb
    links:
      - mysqldb
    command: ['python', 'project/manage.py', 'wait_for_database']
  mysqldb:
    image: mysql
    restart: always
    volumes:
      - /Users/amin/Documents/mysql:/var/lib/mysql
        #  command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=family"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
volumes:
  mysql_data:
